### PR TITLE
fix learn more button link

### LINKED ISSUE #239: Vulnerabilities Incorrect / Links Wrong
We're currently running the latest Harbor version, 2.8.0 and having a couple issues trying to get this plugin working in our backstage instance:

1. The vulnerabilities listed always shows **None** (The vulnerabilities for each of these images should be at least **High** or **Critical**)
Screenshot 2023-08-01 at 9 22 38 PM

2. The **LEARN MORE** link is incorrect
The current link to the artifact in the UI seems to be structured as follows:
`[baseUrl]/harbor/projects/[projectNumber]/repositories/[repoName]/artifacts/[firstArtifactTag]`
The link structure for the latest Harbor release should be:
`[baseUrl]/harbor/projects/[projectNumber]/repositories/[repoName]/artifacts-tab/artifacts/[fullArtifactSha]`

Has anyone else had success with the above in a newer version of Harbor?

### PR DESCRIPTION
**Pull request by locomoco28**
closes #239 in combination with https://github.com/container-registry/backstage-plugin-harbor-backend/pull/110

### CODE REVIEW

File: src/components/HarborRepository/tableHeadings.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export const columns: TableColumn[] = [
     field: 'repoUrl',
     render: (rowData: any) => (
       <Button
-        to={`${rowData.repoUrl}/artifacts/${rowData.tag}`}
+        to={`${rowData.repoUrl}/artifacts-tab/artifacts/${rowData.tag}`}
```
Comment (kamroy) [inline src/components/HarborRepository/tableHeadings.tsx:57]: this url take a digest in param and not a tag ( see api of harbor)

**Review by kamroy — CHANGES_REQUESTED** [review]

File: src/components/HarborRepository/tableHeadings.tsx (hunk 1 above)
Comment (Gamedevboras) [reply src/components/HarborRepository/tableHeadings.tsx:57]: I have tested the same fix and it takes a tag. Is it maybe a different harbor version?

**Review by Gamedevboras — APPROVED** [review]

File: src/components/HarborRepository/tableHeadings.tsx (hunk 1 above)
Comment (locomoco28) [reply src/components/HarborRepository/tableHeadings.tsx:57]: Both, the artifact digest, as well as the artifact name seem to work for me

image

The artifact name is being returned as `tag` by the backend plugin

https://github.com/container-registry/backstage-plugin-harbor-backend/blob/master/src/service/artifact.ts#L46-L48

https://github.com/container-registry/backstage-plugin-harbor-backend/blob/master/src/service/artifact.ts#L109
